# Generated by Django 3.1 on 2020-08-16 11:21

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=35, verbose_name="Name")),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2020, 8, 16, 11, 21, 52, 863441),
                        editable=False,
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                ("link", models.URLField(max_length=128, verbose_name="CV link")),
            ],
        ),
    ]
